### ISSUE TITLE
Paper(s)?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [JosefineAtMath/BoundaryWavelets#2]
Thanks for your work.

A [test](https://github.com/JosefineAtMath/BoundaryWavelets/blob/1.0/test/WaveletTest.py#L26) mentions "the paper", but I haven't found references to any papers, including in [docs](https://vbn.aau.dk/ws/portalfiles/portal/295562519/boundwave.pdf) and [publication page](https://vbn.aau.dk/da/publications/boundarywavelets). Is code itself "the paper" (though one still expects citations)?

I'm looking for boundary wavelets code for [synchrosqueezing](https://github.com/OverLordGoldDragon/ssqueezepy), and this repo may do the trick, but references to relevant theory are needed. Are you open to Pull Requests? Since Python is object-oriented, PascalCase is discouraged, so I reformatted (and fixed a minor bug in tests) in my [fork](https://github.com/OverLordGoldDragon/BoundaryWavelets/).

**Comment by ThomasA** [comment]
Sorry for the late reply. The paper is this one: https://doi.org/10.1007/s42452-020-03858-w
